database:
  - changed-files:
      - any-glob-to-any-file:
          - 'libs/shared/src/migrations/**'
          - 'libs/shared/src/database/**'

cqrs-command:
  - changed-files:
      - any-glob-to-any-file:
          - 'apps/*/src/**/command/**'

cqrs-query:
  - changed-files:
      - any-glob-to-any-file:
          - 'apps/*/src/**/query/**'

dto:
  - changed-files:
      - any-glob-to-any-file:
          - 'apps/*/src/**/dto/**'

entity:
  - changed-files:
      - any-glob-to-any-file:
          - 'libs/shared/src/entities/**'

test:
  - changed-files:
      - any-glob-to-any-file:
          - 'test/**'
          - 'apps/**/*.spec.ts'
          - 'libs/**/*.spec.ts'

documentation:
  - changed-files:
      - any-glob-to-any-file:
          - '*.md'
          - 'docs/**'

ci:
  - changed-files:
      - any-glob-to-any-file:
          - '.github/**'

shared-library:
  - changed-files:
      - any-glob-to-any-file:
          - 'libs/shared/src/**'

service:
  - changed-files:
      - any-glob-to-any-file:
          - 'apps/service/src/**'

back-office:
  - changed-files:
      - any-glob-to-any-file:
          - 'apps/back-office/src/**'
